### ISSUE TITLE
Exercise 2: jQuery Basic Concepts

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/jqfundamentals#1]
Selecting:
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js
1. Select all of the div elements that have a class of "module".
2. Come up with three selectors that you could use to get the third item in the #myList unordered list. Which is the best to use? Why?
3. Select the label for the search input using an attribute selector.
4. Figure out how many elements on the page are hidden (hint: .length).
5. Figure out how many image elements on the page have an alt attribute.
6. Select all of the odd table rows in the table body.

Traversing:
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js
1. Select all of the image elements on the page; log each image's alt attribute.
2. Select the search input text box, then traverse up to the form and add a class to the form.
3. Select the list item inside #myList that has a class of "current" and remove that class from it; add a class of "current" to the next list item.
4. Select the select element inside #specials; traverse your way to the submit button.
5. Select the first list item in the #slideshow element; add the class "current" to it, and then add a class of "disabled" to its sibling elements.

Manipulating:
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js
1. Add five new list items to the end of the unordered list #myList. Hint: for (var i = 0; i<5; i++) { ... }
2. Remove the odd list items
3. Add another h2 and another paragraph to the last div.module
4. Add another option to the select element; give the option the value "Wednesday"
5. Add a new div.module to the page after the last one; put a copy of one of the existing images inside of it.

https://github.com/ayodeleDD/jqfundamentals/tree/master/exercises/exercise2

**Comment by segunadeleye** [comment]
If you have a long line of code such as this, it is advisable to break them into multiple lines. It enhances readability.
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L44

It's best to use the id of the form...don't you think so?
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L56

This can be done with fewer DOM hits
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L64

This can also be done by passing the second element as a second argument to `append` instead of doing calling the method a second time.
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L87

Wednesday is supposed to come after Tuesday. Not after Friday
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L92

Break into multiple lines.
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise2/sandbox.js#L99

Use 2-space indentation for the multi-line method chaining.

**Comment by ayodeleopetumo** [comment]
Code optimized

**Comment by segunadeleye** [comment]
Looks good
