### ISSUE TITLE
Exercise 6: Effects

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/jqfundamentals#3]
Exercises

**Reveal Hidden Text**
Open the file /exercises/index.html in your browser. Use the file /exercises/js/blog.js. Your task is to add some interactivity to the blog section of the page. The spec for the feature is as follows:
1. Clicking on a headline in the #blog div should slide down the excerpt paragraph
2. Clicking on another headline should slide down its excerpt paragraph, and slide up any other currently showing excerpt paragraphs.
   Hint: don't forget about the :visible selector!

**Create Dropdown Menus**
Open the file /exercises/index.html in your browser. Use the file /exercises/js/navigation.js. Your task is to add dropdowns to the main navigation at the top of the page.
1. Hovering over an item in the main menu should show that item's submenu items, if any.
2. Exiting an item should hide any submenu items.

To accomplish this, use the $.fn.hover method to add and remove a class from the submenu items to control whether they're visible or hidden. (The file at /exercises/css/styles.css includes the "hover" class for this purpose.)

**Create a Slideshow**
Open the file /exercises/index.html in your browser. Use the file /exercises/js/slideshow.js. Your task is to take a plain semantic HTML page and enhance it with JavaScript by adding a slideshow.
1. Move the #slideshow element to the top of the body.
2. Write code to cycle through the list items inside the element; fade one in, display it for a few seconds, then fade it out and fade in the next one.
3. When you get to the end of the list, start again at the beginning.

For an extra challenge, create a navigation area under the slideshow that shows how many images there are and which image you're currently viewing. (Hint: $.fn.prevAll will come in handy for this.)

https://github.com/ayodeleDD/jqfundamentals/tree/master/exercises/exercise6

**Comment by segunadeleye** [comment]
You can add links to each of the js files used for the solutions

**Comment by segunadeleye** [comment]
## blog.js

https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/blog.js#L16, https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/blog.js#L17, https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/blog.js#L18
...these can easily make one line.

The code can still be optimised. Hint: Use an except approach.

## slideshow.js

You can get the total slides once instead of getting it every time `showCurrentAndTotalSlide()`  is called https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/slideshow.js#L16

Find a way to only update just the current image position, instead of building the whole text every time. Build slide nav once and update the current image position.

Is this needed? Can't we use `$slideElements` directly?
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/slideshow.js#L22

Since `$slideElements` is being passed around as argument a lot of times, how about making it an instance property/variable.

How about;
`($next.length) ?  $next : ($next = $slideElements.find('li').first())`
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/slideshow.js#L34

<b>NB: Only jQuery objects should have their variable names start with `$`.</b>

**Comment by ayodeleopetumo** [comment]
code optimised

**Comment by segunadeleye** [comment]
## slideshow.js

For the navigation area, instead of adding `div` to the DOM and later adding `span`, what if you build the whole navigation area and add it once to the DOM?

How about setting the initial text for `span` to 1, and then update the position for subsequent slides?

**Comment by ayodeleopetumo** [comment]
code optimised

**Comment by segunadeleye** [comment]
Looks good. However, you need to make very few corrections.

`text()` is a better option here.
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/slideshow.js#L14

Since the initial text position is already set, there's is no need for this.
https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise6/slideshow.js#L30

**Comment by ayodeleopetumo** [comment]
done
